version: '3.9'

networks:
  inception:
    driver: bridge

services:
  mariadb:
    build: requirements/mariadb
    volumes:
      - mariadb:/var/lib/mysql
    container_name: mariadb
    restart: always
    ports:
      - "3306:3306"
    networks:
      - inception
    env_file: .env

  nginx:
    build: requirements/nginx
    volumes:
      - wordpress:/var/www/html
    container_name: nginx
    depends_on:
      - wordpress
    restart: always
    ports:
      - "443:443"
    networks:
      - inception
    env_file: .env

  wordpress:
    build: requirements/wordpress
    volumes:
      - wordpress:/var/www/html
    container_name: wordpress
    restart: always
    expose:
      - "9000"
    depends_on:
      - mariadb
    networks:
      - inception
    env_file: .env


volumes:
  wordpress:
    name: wordpress
    driver: local
    driver_opts:
      type: bind
      o: bind
      device: /home/sleleu/data/wordpress

  mariadb:
    name: mariadb
    driver: local
    driver_opts:
      type: bind
      o: bind
      device: /home/sleleu/data/mariadb