version: '3.9'

networks:
  inception:
    driver: bridge

services:
  mariadb:
    build: requirements/mariadb
    volumes:
      - mariadb:/var/lib/mysql
    container_name: mariadb
    restart: always
    expose:
      - "3306"
    networks:
      - inception
    env_file: .env
    # environment:
    #   - MYSQL_DATABASE=${MYSQL_DATABASE}
    #   - MYSQL_USER=${MYSQL_USER}
    #   - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    #   - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}

  nginx:
    build: requirements/nginx
    volumes:
      - wordpress:/var/www/wordpress
    container_name: nginx
    depends_on:
      - mariadb
      - wordpress
    restart: always
    ports:
      - "443:443"
    networks:
      - inception
    env_file: .env

  wordpress:
    build: requirements/wordpress
    volumes:
      - wordpress:/var/www/wordpress
    container_name: wordpress
    restart: always
    expose:
      - "9000"
    depends_on:
      - mariadb
    networks:
      - inception
    env_file: .env
    # environment: 
    #   - MYSQL_HOST=${MYSQL_HOST}
    #   - MYSQL_DATABASE=${MYSQL_DATABASE}
    #   - MYSQL_USER=${MYSQL_USER}
    #   - MYSQL_PASSWORD=${MYSQL_PASSWORD}


volumes:
  wordpress:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/sleleu/data/wordpress

  mariadb:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/sleleu/data/mariadb