version: '3'

services:
  nginx:
    build: /requirement/nginx
    container_name: nginx
    restart: on-failure
    ports:
      - 443:443
    volumes:
      - /home/sleleu/data/site:/var/www/html
    networks:
      - inception
    dockerfile: Dockerfile
    env_file: .env