version: '3'

networks:
  inception:
    name: inception
    driver: bridge

services:
  mariadb:
    build: requirements/mariadb
    volumes:
      - mariadb_vol:/var/lib/mysql
    container_name: mariadb
    restart: always
    expose:
      - "3306"
    networks:
      - inception
    env_file: .env
    environment:
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}

  nginx:
    build: requirements/nginx
    volumes:
      - wordpress_vol:/var/www/wordpress
    container_name: nginx
    restart: always
    ports:
      - "443:443"
    networks:
      - inception
    env_file: .env

  wordpress:
    build: requirements/wordpress
    volumes:
      - wordpress_vol:/var/www/wordpress
    container_name: wordpress
    restart: always
    expose:
      - "9000"
    depends_on:
      - mariadb
    networks:
      - inception
    env_file: .env
    environment: 
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_HOSTNAME=${MYSQL_HOSTNAME}

volumes:
  mariadb_vol:
  wordpress_vol: